title: ""
description: ""
url: https://faenuccio-teaching.github.io
baseurl: "/Beijing_Jun26"
repository: faenuccio-teaching/Beijing_Jun26
layout: default
nav_enabled: true
# Enable heading anchors
heading_anchors: true

# Aux links appear in the upper right
aux_links_new_tab: false

remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
  
keep_files:
  - docs
  - docbuild

show_downloads: true

# nav:
#   - title: Home
#     url: /
# 
#   - title: GitHub
#     url: https://github.com/faenuccio-teaching/Beijing_Jun26

